site_name: "Windows 11 + PowerShell Lab"
site_description: >-
  This repository is a reference hub for building, securing, and managing a
  Windows environment. It combines practical setup notes, security principles,
  and PowerShell learning resources into one organized space, published as
  a live site using MkDocs.

theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - search.highlight
    - search.suggest
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  logo: assets/studio-teknabu-logo.webp
  favicon: assets/favicon-32x32.png

plugins:                # ← OUTDENTED to root (very important)
  - search
  - gen-files
  - simple-hooks:
      on_files:
        - buildtools.gen_section_indexes:build_all_indexes
  - awesome-pages
  - roamlinks

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra_css:
  - assets/theme.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: "https://github.com/Sammy-John/windows11-powershell-lab"
