site_name: Win11 Lab
site_description: Windows 11 Lab notes, guides, and cheatsheets
site_url: https://sammy-john.github.io/windows11-powershell-lab

repo_url: https://github.com/Sammy-John/windows11-powershell-lab
edit_uri: edit/main/docs/

theme:
  name: material
  logo: images/studio-teknabu-logo.webp
  favicon: images/studio-teknabu-logo.webp
  alette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.top
    - toc.integrate
    - content.code.copy

nav:
  - Home: index.md

docs_dir: docs

extra_css:
  - stylesheets/extra.css

