site_name: Windows11 + Powershell Lab
site_url: https://sammy-john.github.io/windows11-powershell-lab/
repo_url: https://github.com/Sammy-John/windows11-powershell-lab
repo_name: Sammy-John/windows11-powershell-lab
edit_uri: edit/main/docs/

# default dirs (explicit for clarity)
docs_dir: docs
site_dir: site

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      exclude:
        - changelog.md   # we copy this into docs/ during build
  - glightbox

# …(theme, extensions, extra) keep as you had them…
