name: Build MkDocs into /docs

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'    # prevent loops when committing built files
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for git dates)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure unshallow (safety)
        run: |
          git fetch --prune --unshallow || true
          echo "is-shallow? $(git rev-parse --is-shallow-repository || echo unknown)"
          git log -1 --oneline || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs + plugins
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs-material \
            mkdocs-minify-plugin \
            mkdocs-git-revision-date-localized-plugin \
            mkdocs-glightbox

      - name: Sync changelog into src/
        run: |
          mkdir -p src
          if [ -f "changelog.md" ]; then
            cp -f changelog.md src/changelog.md
            echo "Copied changelog.md -> src/changelog.md"
          else
            echo "::warning::Root changelog.md not found; skipping copy"
          fi

      - name: Build MkDocs (strict, output to /docs)
        run: mkdocs build --strict --clean

      - name: Commit built site to main (docs/)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Build MkDocs site"
          file_pattern: docs/**
