name: Build & Deploy MkDocs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # needed for deploying to gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs + plugins
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs-material \
            mkdocs-minify-plugin \
            mkdocs-git-revision-date-localized-plugin \
            mkdocs-glightbox

      - name: Sync changelog into docs/
        run: |
          mkdir -p docs
          if [ -f "changelog.md" ]; then
            cp -f changelog.md docs/changelog.md
            echo "Copied changelog.md -> docs/changelog.md"
          else
            echo "::warning::Root changelog.md not found; skipping copy"
          fi

      - name: Build MkDocs (strict)
        run: mkdocs build --strict

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
          force_orphan: true
