name: Deploy MkDocs via GitHub Actions

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history for git dates)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install MkDocs + plugins
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs-material \
            mkdocs-minify-plugin \
            mkdocs-git-revision-date-localized-plugin \
            mkdocs-glightbox

      - name: Copy changelog.md into docs/
        run: |
          mkdir -p docs
          if [ -f "changelog.md" ]; then
            cp -f changelog.md docs/changelog.md
            echo "Copied changelog.md -> docs/changelog.md"
          fi

      - name: Build MkDocs (strict)
        run: mkdocs build --strict --clean

      # Optional: stamp the build so you can verify the deployed version
      - name: Stamp build
        run: |
          echo "Built from $GITHUB_SHA at $(date -u +'%Y-%m-%dT%H:%M:%SZ')" > site/build.txt
          cat site/build.txt

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
